### PR TITLE
Use Debian Sid for up-to-date packages instead of Bullseye stable repos

### PR DESCRIPTION
**Pull request by ADawesomeguy**
Based on comments from @Ta180m regarding more up-to-date compilers and runtimes.

### CODE REVIEW

**Comment by Ta180m** [comment]
Have you been able to get this to build? I've been running `podman build` for about 10 minutes now and it's still on the `apt install` step.

**Comment by Ta180m** [comment]
Nevermind, it finally finished building and I got a 3.17GB image. Not bad.

**Comment by ADawesomeguy** [comment]
Building the image takes me a couple minutes, but yes, the build is functional as far as I know. I'll update with using `apt-get` instead of `apt` due to the fact that building the Docker image is technically a script.

**Comment by Ta180m** [comment]
@ADawesomeguy So are we going with Sid or Bullseye for the base image?

**Comment by ADawesomeguy** [comment]
Think we should go with Sid because although it isn't technically stable, it doesn't tend to break often as far as I know and it'll have the most up-to-date compilers that Debian offers. Not much different than using Arch or something as I see it.

**Review by ADawesomeguy — COMMENTED** [review]
Good thinking 👍🏽

**Pull request merged**
