### PR TITLE
Add basic (functional) Dockerfile

### PR DESCRIPTION
**Pull request by ADawesomeguy**
Dockerization! 🎉

### CODE REVIEW

**Comment by Ta180m** [comment]
Why not OpenJDK 17? Is 11 the latest version available?

**Comment by ADawesomeguy** [comment]
Honestly, no reason, I can go ahead and update it I think. I'll also see if I can modify the Debian repos to use unstable so that I can get similar package versions to something like Arch Linux.

**Comment by Ta180m** [comment]
Eh, let's keep the stable repos, since we don't really want to be using Debian unstable in production. Then again, using Arch Linux in production is pretty risky too (but fun!).

**Comment by Ta180m** [comment]
I'll push a commit to use OpenJDK 17 (and some Podman-related fixes)

**Comment by Ta180m** [comment]
Is it normal for Podman builds to take so long? I've been building this Dockerfile for the past 10 minutes and it's still on the `apt install` step.

**Pull request merged**
